Fix workflow file

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,14 +30,19 @@ jobs:
         run: |
           git clone https://github.com/${{github.repository}} --branch=19.0 --depth=1 main
           for dir in ${ALL_CHANGED_FILES}; do
+            echo "A file in module directory ${dir} has changed"
             if [ -f "${dir}/__manifest__.py" ]; then
-              echo "$dir module was changed"
+              echo "Found __manifest__.py in ${dir}"
               version_in_branch=$(grep 'version' "${dir}/__manifest__.py" | awk '{print($2)}')
               echo "Version ${version_in_branch} in module ${dir}"
               version_in_main=$(grep 'version' "main/${dir}/__manifest__.py" 2>/dev/null | awk '{print($2)}' || echo "")
               echo "Version ${version_in_main} in main"
-            else
-              echo "Ignoring directory ${dir} as it does not contain __manifest__.py"
+              if [ "${version_in_branch}" = "${version_in_main}" ]; then
+                echo "Versions match! Aborting!"
+                exit 1
+              else
+                echo "Versions do not match, everything okay."
+              fi
             fi
           done
 
